name: R pkgdown Multi Version docs
author: Insights Engineering
description: Generates multisite R documentation created with pkgdown.
branding:
  icon: 'anchor'
  color: 'orange'
inputs:
  path:
    description: Path to package's root
    required: false
    default: "."
  default-landing-page:
    description: |
      The default branch or tag on gh-pages that corresponds to the landing page.
      For instance, if your root index page on gh-pages is built using the 'main'
      branch, then the root page of the website will correspond to this page.
      If 'latest-tag' is selected, then the latest version will become the default.
    default: main
    required: false
  branches-or-tags-to-list:
    description:
      Which branches or tags should be listed under the
      'Versions' dropdown menu on the landing page?
      This input should be a regular expression in R.
    required: false
    default: |
      ^main$|^devel$|^pre-release$|^v([0-9]+\\.)?([0-9]+\\.)?([0-9]+)$

runs:
  using: 'composite'
  steps:
    - name: Run multi-version site creation script
      run: |
        source(file.path(
          Sys.getenv("GITHUB_ACTION_PATH"), "core.R")
        )
        update_content(
          docs_path = "${{ inputs.path }}",
          refs_to_list = "${{ inputs.branches-or-tags-to-list }}"
        )
      shell: Rscript {0}

    - name: Create symlink for latest-tag
      run: |
        cd ${{ inputs.path }}
        set +o pipefail
        latest_tag=$(ls -1d * \
          | grep -E "^v([0-9]+\.)?([0-9]+\.)?([0-9]+)$" \
          | sort -t "." -k1,1n -k2,2n -k3,3n \
          | tail -1)
        set -o pipefail
        [[ "${latest_tag}" != "" ]] \
          && ln -sf ${latest_tag} latest-tag \
          || echo "No tags found, not creating symlink for latest tag"
      shell: bash

    - name: Create redirect page
      run: |
        cd ${{ inputs.path }}
        cp "${GITHUB_ACTION_PATH}/redirect.html" index.html
        perl -p -i -e \
          "s@REDIRECT_PAGE@${{ inputs.default-landing-page }}@g" \
          index.html
        touch .nojekyll
      shell: bash

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Built site for ${{ github.event.repository.name }}@${{ github.sha }}"
        repository: ${{ inputs.path }}
        file_pattern: "."
        commit_user_name: github-actions
        commit_user_email: 41898282+github-actions[bot]
